spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financialdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Create database tables on startup
    show-sql: true
  sql:
    init:
      mode: always # Always execute schema.sql on startup
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: transactions-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"